version: '2'

services:
  sia:
    build: 
      context: ./sia
    volumes:
      - ./sia-data/:/var/sia-data
      - ./minio-data/:/var/minio-data
    restart:
      always
  minio:
    build:
      context: ./minio
    environment:
      - SIA_CACHE_MAX_SIZE_BYTES=10000000000  # 10GB
      - SIA_CACHE_DIR=/var/minio-data/sia_cache
      - SIA_DB_FILE=/var/minio-data/sia.db
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=welovesia
      - SIA_DAEMON_ADDR=sia:19980
      - SIA_BACKGROUND_UPLOAD=1
      - SIA_DEBUG=1
    volumes_from:
      - sia
    links:
      - sia
    ports:
      - "9000:9000"
